language: node_js
node_js:
  - '12'

dist: trusty

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install -g codecov

script:
  - npm test && codecov

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email: false
